twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel
        timeout: 0.5
        priority: 10

      key_board:
        topic: cmd_vel
        timeout: 0.5
        priority: 10